[project]
name = "satya-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "fastapi>=0.135.3",
    "feedparser>=6.0.12",
    "nepali-nlp",
    "nepalitokenizers>=0.0.2",
    "rdflib>=7.6.0",
    "spacy>=3.8.14",
    "transformers>=5.4.0",
    "uvicorn>=0.42.0",
]

[tool.uv.sources]
nepali-nlp = { git = "https://github.com/sushil79g/Nepali_nlp.git" }
